### ISSUE TITLE
Poses

### ISSUE THREAD

**Issue by Colorfingers** [makehuman-js/makehuman-data#2]
How are poses accomplished?  The Tpose seems to be broken and I would like to fix it.  I've dug around in src/json/poses/poses.json with little luck trying to figure out what is wrong with it.

Also, are you creating the target.bin based from the target.npz file?  Where are the sources?

Thank you for all this.  It is wonderful.

**Comment by wassname** [comment]
Thanks, it's great that you want to have a go and make some changes. Feel free to ask me about things, since not many people have used it, meaning it might not be presented or explained that well. Any PR's are welcome.

For poses I got the makehuman transformation matrix and converted it to a quarternion for threejs skeletons. (search for "quaternion_from_matrix" in [Export_poses_to_json.ipynb](https://github.com/makehuman-js/makehuman-data/blob/a67855e/scripts/notebooks/Export_poses_to_json.ipynb)). I end up with a json that can be used to set the position and rotation of each joint in threejs. 

The poses.json is used by [`setPoses` in `human.js`](https://github.com/makehuman-js/makehuman-js/blob/0efa832d6255341172a446450f7a14482267e684/src/js/human/human.js#L453)

**Comment by wassname** [comment]
For targets, it was quite large and slow to load as json so I packed it into a binary format of float32 values (making it ~200mb for all targets). The code for that is in [Export_targets_to_bin.ipynb](https://github.com/makehuman-js/makehuman-data/blob/a67855e/scripts/notebooks/Export_targets_to_bin.ipynb).

The code that loads it is [makehuman-js/src/js/human/targets.js](https://github.com/makehuman-js/makehuman-js/blob/f9225f7/src/js/human/targets.js#L220). Then in applyTargets we apply it by doing some multiplication.

**Comment by wassname** [comment]
The sources for the post/target data are the makehuman python package. Instructions to get the exact version I used are in the readme, namely, "run `./scripts/vendors/get_vendor_libs.sh`". This just clones a particular version of makehuman-python, downloads, and compiles the assets.

However it just get's the assets from an ftp, so it's possible they may be updated by the makehuman project.

**Comment by Colorfingers** [comment]
Wow, what a quick response!  I am very motivated into helping on this project.  I appreciate all your help and I will be sure to have more questions.  I will continue to dig and learn from the code before bothering you. Thank you. Do you have any suggestions on applying a custom skeleton?

**Comment by wassname** [comment]
Sounds great.

It looks like the skeleton is [exported in the human.json](https://github.com/makehuman-js/makehuman-data/blob/master/scripts/notebooks/Export_base_human_to_threejs_json.ipynb) (search for bones), and also when [exporting the proxies](https://github.com/makehuman-js/makehuman-data/blob/master/scripts/notebooks/Export_proxies_to_threejs.ipynb) (search for bones). 

From memory it's possible but I forget exactly how (it was a while ago). I think you would need to work out how to set a different skeleton on the makehuman python object by trying and reading the makehuman (python) code. I can't see or remember how to do it off the top of my head, but if you get stuck with that part I can have a look or you can ask the makehuman community. Then add the code to change skeleton before the human and proxies export notebooks.

**Comment by Colorfingers** [comment]
OK, I'm back.  I have searched the entire code base and can only find one reference to "tpose" which is in the poses.json file.  Here's the thing I cannot figure out.  I remove the tpose from poses.json, delete my browser cache and refresh the page.  I still have tpose in the menu and it still reacts with the same error.  All I can think is that there has to be some reference in the targets.bin file.  This is the only source I cannot search.

I find the error in makehuman.js lines 64810, 64812

                    if (!bone) console.error('couldnt find bone', boneName);
                    // Tween the pose
                    var data = pose[bone.name];

The bone in question is metatarsal1.R

First I tried removing it from the poses.json file to see if it would progress through the bones and continue or error to another.  Yet, it does not.  So I removed the tpose completely from the json file and we are still getting data.  Very confusing.

**Comment by wassname** [comment]
That's a good question, I'll have a good at it tomorrow though when I'm back home.

**Comment by wassname** [comment]
> same error

What is the error, I assumed it was a visual anomaly. Perhaps you could copy and paste the stack trace?

There may be something about your setup that's causing it, but what is your setup? Ideally you can describe it out well enough that I can replicate it and debug it if needed. Otherwise I'll have to speculate about how you've got it setup which will involve lots of guessing. 

No worries, it's a pretty big project to get your head around and it takes time. Well here's my guess:

Are you using makehuman-js-example? If so you are probably using the poses.json from npm, not the one you are looking at. To confirm this you can go to the chrome debugger for the makehuman-js-example webapp and try looking in the network manager or source tabs to find poses.json. 

The way it may be working is that `makehuman-js-example` uses the `makehuman-js` package which uses the `makehuman-data` package. That last one download poses.json from npmjs.com. (So it's uses one from the node_modules/makehuman-data folder).

Do you think that might be it?

Here's how I run it when I want to develop it: So run this in a development environment you can make local clones of makehuman-data, makehuman-js, and makehuman-js-example. Then install the first two using [npm link](http://justjs.com/posts/npm-link-developing-your-own-npm-modules-without-tears). That way you are calling them like packages but you are using local versions you can modify and inspect. This is pretty handy way of developing multiple npm modules.

**Comment by Colorfingers** [comment]
The error occurs on your site as well in both the main page and the example... just try the "tpose"  pose.  All the other poses work as expected.  I can remove the pose.json file and it has no effect whatsoever.  The data appears to be coming from some other source.  I've searched the folders to ensure there is only one copy. I'm a bit baffled. 

![image](https://user-images.githubusercontent.com/42556646/44562491-b6059500-a70e-11e8-8b80-2c945f8cdf4e.png)

![image](https://user-images.githubusercontent.com/42556646/44562566-febd4e00-a70e-11e8-8401-19fa69646de0.png)

Thanks for the tips... I'll look at that and give it a try.  I'll check to ensure the path/vesion is correct.  I'm not getting any errors otherwise.  It's just the "tpose" pose position that throws the error.

I'm amazed at how deep this rabbit hole is.  I'm dedicated to wrapping my head around it though.  It might take me a while.  Thank you for your help and insight.  Here's a screenshot of my structure:

![image](https://user-images.githubusercontent.com/42556646/44562776-0a5d4480-a710-11e8-81ec-1e362228a593.png)

My paths:

    <script src="ajax/three.js" charset="utf-8"></script>
    <script src="ajax/lodash.min.js"></script>
    <script src="ajax/dat.gui.min.js"></script>
    <script src="ajax/Stats.min.js"></script>
    <script src="ajax/nanobar.min.js"></script>
    <script src="ajax/FileSaver.min.js"></script>
    <script src="node_modules/three/examples/js/controls/OrbitControls.js"></script>
    <script src="node_modules/three/examples/js/renderers/Projector.js"></script>
    <script src="node_modules/three/examples/js/loaders/BVHLoader.js"></script>
    <script src="node_modules/three/examples/js/Detector.js"></script>
    <script src="node_modules/makehuman-js/dist/makehuman.js" charset="utf-8"></script>
    <script src="js/main.js" charset="utf-8"></script>
    <script type="text/javascript">

    var loadUrls = {
        modeling_sliders: 'node_modules/makehuman-data/src/json/sliders/modeling_sliders.json',
        resources: 'data/resources.json'
    }
        resources.baseUrl = "data/"

**Comment by wassname** [comment]
Oh I see what you mean now! Thanks for showing me.

Yeah it looks like tpose wants some metavarsall bones that are not in any of the skeletons/rigs. That's weight. So there's no way we can provide those bones :O

So one way is just to ignore bones we don't have, e.g. [makehuman-js#6](https://github.com/makehuman-js/makehuman-js/pull/6) another is to remove the missing bones from poses.json like you are testing. 

So why arn't poses.json changes showing up. I think I see. So it's getting the js files from importing the makehuman-js-data/ package, so from `node_modules/makehuman-js-data/src/js...`. That includes poses.js. For the images, bin and others it's getting them from the baseurl. Then the json for the ui is coming from loadUrls. Sorry for the confusion it's just that some are loaded as library code and some as assets but they come from the same package.

Yeah it would take me a week to get my head around I think. Sorry if it's confusing, I tried to make it clean and clear but it's hard to do on your own because we all have our own style. Any improvements to that are welcome, even just clearer comments in the example.

**Comment by Colorfingers** [comment]
I'm pretty good at creating documentation.  I can help with that once I get a better grip on this.  I have absolutely no experience with Python so that is to my detriment.  Your Javascript is definitely heavy weight.  I would guess you have a degree in Computer Science.  You have allot of good comments in the code.   

I'm I missing something here?  The example is pointing to makehuman.js yet your commit is editing human.js.  I can tell there are differences between these versions.  The application fails if I try to use human.js instead.  I applied your edit to makehuman.js and "tpose" is executing as expected with errors. If I remember correctly I couldn't find makehuman.js in the downloaded repositories from GIT so I downloaded it from your site to get the example to work.

**Comment by Colorfingers** [comment]
My guess is that it isn't reading poses.json at all... that's my experience.  If I remove it, there are no other copies to read, and the poses are still working then there has to be some other data source.  I deleted my browser cache so it can't be referencing a cache copy.  If you could test this on your example site to confirm this....

**Comment by Colorfingers** [comment]
I am seeing a new error though that might help us understand where the data is coming from...  

human.js:11 Uncaught SyntaxError: Unexpected identifier

Which is "import _ from 'lodash'"

**Comment by wassname** [comment]
> I would guess you have a degree in Computer Science. You have allot of good comments in the code.

Thanks!, I'm just self taught (but have been programming for a while from a physics background) so it's good to get some feedback.

> I'm I missing something here? 

Oh yeah I didn't explain the build process, I guess we've been talking about differen't files. So I'm programming in es6 javascript then packaging and transpiling that using webpack. This is so that it becomes one compressed file that's compatible with more browsers. Webpack takes human.js, all imported files (included imported json files like pose.json) and turns it into one big file (makehuman.js).  So that's when poses.json gets included. To update the makehuman.js file you run webpack using `npm run build`. 

If you haven't done that before then short instructions are

- go to the makehuman-js source and install local dev dependencies with `npm install --dev`. 
- Then install webpack globally `npm i -g webpack` so it's available on the commandline. 
- Then run webpack with [npm scripts command](https://github.com/makehuman-js/makehuman-js/blob/master/package.json#L16): `npm run build`. 

The reason I haven't commited makehuman.js to the repo is that I don't want to confuse things with the code being written twice, and instead I just regenerate it from the source with webpack. You can even have it regenerate every time you make changes with `npm run watch`. 

Hopefully that all makes sense, but feel free to clarify.

**Comment by wassname** [comment]
Yeah I'll try it on my machine.  

Specifically I think you're using  poses.json from `./node_modules/makehuman-data/src/js/poses.json` or `./node_modules/makehuman-js/node_modules/makehuman-data/src/js/poses.json` (relative to your main folder). And it's being included into makehuman.js when webpacking it. Sorry I didn't realise that you didn't have webpack set up, so we were talking about differen't files. I know it's yet another system to learn but It's way easier to work with the original source files and it will make more sense.

I guess instructions on the development process are needed in the readme! I haven't read it myself but this tutorial tries to go through development with webpack (although it may be too much info) https://survivejs.com/webpack/introduction/. A shorter intro is [here](https://codeburst.io/easy-guide-for-webpack-2-0-from-scratch-fe508a3ce44e).

**Comment by wassname** [comment]
I added instruction for developing to the makehuman-js-example readme, hopefully that makes it a little clearer?

**Comment by Colorfingers** [comment]
I was wondering what webpack was referring to in the makehuman.js file.  I kept trying to find some other file and then just assumed that the target.bin must be what it was referring to.  I just couldn't figure how it was being brought in.  Now I see.  I will have to think about this a bit more in depth while I dig into this new concept.  Thank you for your patience.

**Comment by wassname** [comment]
No worries, thanks for trying it out!

**Comment by Colorfingers** [comment]
> Sounds great.
> 
> It looks like the skeleton is [exported in the human.json](https://github.com/makehuman-js/makehuman-data/blob/master/scripts/notebooks/Export_base_human_to_threejs_json.ipynb) (search for bones), and also when [exporting the proxies](https://github.com/makehuman-js/makehuman-data/blob/master/scripts/notebooks/Export_proxies_to_threejs.ipynb) (search for bones).
> 
> From memory it's possible but I forget exactly how (it was a while ago). I think you would need to work out how to set a different skeleton on the makehuman python object by trying and reading the makehuman (python) code. I can't see or remember how to do it off the top of my head, but if you get stuck with that part I can have a look or you can ask the makehuman community. Then add the code to change skeleton before the human and proxies export notebooks.

Just for anyone's need... I  moved early this year and am just getting back.  After digging into things I see that what I am likely after is the rigging... not the bones.  I see we can choose the actual rig when running the notebook.  "rigfile = 'data/rigs/default.mhskel'"
