### ISSUE TITLE
IO

### ISSUE THREAD

**Issue by Colorfingers** [makehuman-js/makehuman-data#3]
I'm having a bit of trouble trying to figure out what we can do with this.  I'm looking at the scene and I find that all of Makehuman's entities are wrapped in an array as an object in the scene.  The obj download is cloning the io object from the array and converting it to JSON.  None of the transforms are being cloned in the function so we just get the base model.  I'm trying to figure out how this working.  

It appears that none of the arguments are available because we are using ES6 to create Makehuman.  When I say arguments I mean that the fields for arguments contain the following notice: "Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)]"  

Googling around leads me to believe this is because of the conversion from E6 to E5.

From what I can tell there are 5 objects in the scene.  2 are undefined and I have no way of telling what they are.  Then there is the camera object, the light object and an object created by this these lines:
        // HUMAN
        this.human = new makehuman.Human(this.resources);
        self.scene.add(self.human);

Do you have any ideas on how we can export the model as viewed in the scene?

Thank you...

Here's a view of the self.scene.human object:

![io](https://user-images.githubusercontent.com/42556646/45244528-09e6b100-b2ad-11e8-8cb1-4e41a2405540.PNG)

**Comment by wassname** [comment]
It's good your still having a go. I'm having trouble understanding the context, and what happened, perhaps you could explain what you are trying to do, and the steps so I can replicate it.

I guess you are in the web interface, and are trying to export a transformed makehuman object using `app.human.io.toObj()` or similar from the console? But I'm not sure how you are calling it, what arguments you are using, and when that error comes up.

It works for me. For example If I go to the example site, transform the human into a child, then click exportobj at the bottom of the gui, I get a test.obj download. If I open this in blender (file, import, wavefront) I get the transformed child. So the export worked and did include transforms.

**Comment by Colorfingers** [comment]
After examining it I see you are correct.  I guess that I expected the pose to exported as well...

**Comment by Colorfingers** [comment]
I have one other question on this issue... Can you explain just what the helper function in toObj is performing.  My guess is that we clone the mesh and are gathering the vertices that have changed and are applying it to the mesh.  It looks like I would have to write a much more complicated helper to export as  GTfl or Collada formats.

**Comment by wassname** [comment]
No worries, it got big and complicated and I think it's good to have someone else look into it. I've forgotten some of the stuff I did already but yeah I don't think I had poses be exported. I think that's because they are not applied to the mesh but applied after wards in a pre-rendering stage. It should be possible to export poses to but I'm not sure how long it would take. In our renderer, threejs, poses are directions (quaternions) for the bones, and then parts of the body (mesh) are attached to each bone. The clothes aren't exported either.

> It looks like I would have to write a much more complicated helper to export as GTfl or Collada formats.

I modified OBJExporter from threejs, so potentially you could start with exporters that threejs has an modify them, but yeah it might be a day or two to work out how the ColladaExporter works in threejs so you can make changes.

> Can you explain just what the helper function in toObj is performing.

Do you mean the helper option, otherwise I'm not sure what your referring to. So makehuman has a human body, then it has some invisible meshes attached to it: hair helper, dress helpers etc. These are invisible extension to the human body that you can attach clothes or hair to. Like a person walking around with invisible coat hangers and velcro tabs. When the human is morphed, so are the helpers, then you stretch the clothes to fit the helper, and this makes sure the clothes fit the morphed human. 

So the [helper option](https://github.com/makehuman-js/makehuman-js/blob/f747095c13/src/js/human/human.js#L85) decides if you want to export these too, or strip them away. They look like junk, but they might help someone debugging or doing further morphing in another program.

**Comment by wassname** [comment]
toObj was a recent function without comments, so I added some: https://github.com/makehuman-js/makehuman-js/commit/399f04c62fa9560f34a836c56607744c3fb97f01 . If you can think of better/extra comments then that's great and go ahead and make a PR to improve them.

**Comment by Colorfingers** [comment]
Nice... thank you.  I think I understand now.  This is very helpful.

**Comment by wassname** [comment]
Awesome, glad I could help.

**Comment by Colorfingers** [comment]
What are the parameters with the helpers?

 var helpers = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : true;

**Comment by wassname** [comment]
No sure where that code comes from, it's webpacked code right? It'll probably be clearer if you look at the source code before it's been transpiled. 

But I think that's just setting the default value of helpers to true?

(for example you find the corresponding source code by webpacking with a source map, and looking at in chrome, then it will show original source code)
